services:
  kafka:
    image: apache/kafka:4.0.0
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,INTERNAL://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-init:
    image: apache/kafka:4.0.0
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command:
      - >
        until /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic tweets.raw --partitions 1 --replication-factor 1 &&
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic tweets.clean --partitions 1 --replication-factor 1;
        do echo "waiting for kafka to be ready..."; sleep 2; done

  extractor-service:
    build:
      context: .
      dockerfile: extractor-service/Dockerfile
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER}

  processor-service:
    build:
      context: .
      dockerfile: processor-service/Dockerfile
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER}

  sink-service:
    build:
      context: .
      dockerfile: sink-service/Dockerfile
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER}
      MONGO_URI: ${MONGO_URI}