// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sentiment.proto

package sentimentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeSentimentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeSentimentRequest) Reset() {
	*x = AnalyzeSentimentRequest{}
	mi := &file_sentiment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeSentimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeSentimentRequest) ProtoMessage() {}

func (x *AnalyzeSentimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentiment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeSentimentRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeSentimentRequest) Descriptor() ([]byte, []int) {
	return file_sentiment_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeSentimentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AnalyzeSentimentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"` // vader : positive, negative, neutral
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeSentimentResponse) Reset() {
	*x = AnalyzeSentimentResponse{}
	mi := &file_sentiment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeSentimentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeSentimentResponse) ProtoMessage() {}

func (x *AnalyzeSentimentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentiment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeSentimentResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeSentimentResponse) Descriptor() ([]byte, []int) {
	return file_sentiment_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeSentimentResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AnalyzeSentimentResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_sentiment_proto protoreflect.FileDescriptor

const file_sentiment_proto_rawDesc = "" +
	"\n" +
	"\x0fsentiment.proto\x12\tsentiment\"-\n" +
	"\x17AnalyzeSentimentRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"F\n" +
	"\x18AnalyzeSentimentResponse\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score2o\n" +
	"\x10SentimentService\x12[\n" +
	"\x10AnalyzeSentiment\x12\".sentiment.AnalyzeSentimentRequest\x1a#.sentiment.AnalyzeSentimentResponseBAZ?github.com/rayhan889/mock-streamprocess/sentimentpb;sentimentpbb\x06proto3"

var (
	file_sentiment_proto_rawDescOnce sync.Once
	file_sentiment_proto_rawDescData []byte
)

func file_sentiment_proto_rawDescGZIP() []byte {
	file_sentiment_proto_rawDescOnce.Do(func() {
		file_sentiment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentiment_proto_rawDesc), len(file_sentiment_proto_rawDesc)))
	})
	return file_sentiment_proto_rawDescData
}

var file_sentiment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sentiment_proto_goTypes = []any{
	(*AnalyzeSentimentRequest)(nil),  // 0: sentiment.AnalyzeSentimentRequest
	(*AnalyzeSentimentResponse)(nil), // 1: sentiment.AnalyzeSentimentResponse
}
var file_sentiment_proto_depIdxs = []int32{
	0, // 0: sentiment.SentimentService.AnalyzeSentiment:input_type -> sentiment.AnalyzeSentimentRequest
	1, // 1: sentiment.SentimentService.AnalyzeSentiment:output_type -> sentiment.AnalyzeSentimentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sentiment_proto_init() }
func file_sentiment_proto_init() {
	if File_sentiment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentiment_proto_rawDesc), len(file_sentiment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentiment_proto_goTypes,
		DependencyIndexes: file_sentiment_proto_depIdxs,
		MessageInfos:      file_sentiment_proto_msgTypes,
	}.Build()
	File_sentiment_proto = out.File
	file_sentiment_proto_goTypes = nil
	file_sentiment_proto_depIdxs = nil
}
