# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentiment.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'sentiment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsentiment.proto\x12\tsentiment\"\'\n\x17\x41nalyzeSentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"8\n\x18\x41nalyzeSentimentResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x32o\n\x10SentimentService\x12[\n\x10\x41nalyzeSentiment\x12\".sentiment.AnalyzeSentimentRequest\x1a#.sentiment.AnalyzeSentimentResponseBAZ?github.com/rayhan889/mock-streamprocess/sentimentpb;sentimentpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentiment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?github.com/rayhan889/mock-streamprocess/sentimentpb;sentimentpb'
  _globals['_ANALYZESENTIMENTREQUEST']._serialized_start=30
  _globals['_ANALYZESENTIMENTREQUEST']._serialized_end=69
  _globals['_ANALYZESENTIMENTRESPONSE']._serialized_start=71
  _globals['_ANALYZESENTIMENTRESPONSE']._serialized_end=127
  _globals['_SENTIMENTSERVICE']._serialized_start=129
  _globals['_SENTIMENTSERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
